"""
Build the module-level practice PDFs from the practice pages, as in ECON 441.

    python3 scripts/build_module_practice.py                 # every module
    python3 scripts/build_module_practice.py economists-toolkit

Parses practice/practiceNN.qmd (problems, MCQs, solutions), converts the
markdown with pandoc, and writes practice/practice-<slug>.tex (problems
only) plus practice/practice-<slug>_solutions.tex (problems with solutions);
the Makefile target `module-practice` then compiles both with LuaLaTeX as
tagged PDF/UA-2 and veraPDF-gates them. The qmd pages stay the single
source: nothing is retyped here, and the MCQ answer letters are read back
from the answer="" attributes. Figures (SVGs under slides/img) are converted
to PDF under practice/img/ with rsvg-convert, as in the deck build, and keep
their fig-alt as the PDF alt text.
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRACTICE = ROOT / "practice"

# Module slug -> (title, practice page numbers). A module is listed once
# every page in it is published; add the matching entry to MODULE_PRACTICE
# in syllabus/create_schedule.py so the module page links the PDFs.
MODULES = {
    "economists-toolkit": ("The Economist's Toolkit", ["03", "04"]),
    "firms-as-price-setters": ("Firms as Price Setters",
                               ["06", "07", "08", "09", "10", "11", "12", "13"]),
}

PANDOC = [shutil.which("pandoc")] if shutil.which("pandoc") else ["quarto", "pandoc"]

PREAMBLE = r"""% !TEX program = lualatex
% Generated by scripts/build_module_practice.py - do not edit by hand.
\DocumentMetadata{
  pdfstandard=UA-2,
  pdfversion=2.0,
  lang=en-US,
  tagging=on
}
\documentclass[11pt]{article}
\usepackage[letterpaper, margin=0.8in, top=0.6in, bottom=0.6in]{geometry}
\usepackage{fontspec}
\setmainfont{Fira Sans}
\usepackage{amsmath}
\usepackage{amssymb}
% Fira Sans has no U+2032; an unmapped glyph fails PDF/UA-2 (.notdef)
\usepackage{newunicodechar}
\newunicodechar{′}{\ensuremath{'}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{calc}
\usepackage{etoolbox}
\usepackage{xcolor}
\usepackage{graphicx}
\definecolor{accent}{HTML}{BF5700}
% pandoc emits \tightlist on compact lists
\providecommand{\tightlist}{\setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{titlesec}
\titleformat{\section}{\large\bfseries\color{accent}}{}{0pt}{}
\titlespacing*{\section}{0pt}{14pt}{4pt}
\titleformat{\subsection}{\normalsize\bfseries}{}{0pt}{}
\titlespacing*{\subsection}{0pt}{10pt}{2pt}
\usepackage{hyperref}
\hypersetup{pdftitle={TITLE_HERE}, pdfauthor={Div Bhagia}, hidelinks}
\pagestyle{plain}
\setlength{\parindent}{0pt}
\setlength{\parskip}{4pt}
\begin{document}
{\LARGE\bfseries\color{accent} HEADER_HERE}\hfill{\large ECON 201}
\vspace{4pt}
"""

DETAILS = re.compile(
    r'\n?<details class="solution">\s*<summary>Solution</summary>(.*?)</details>\n?',
    re.DOTALL)
MCQ_BLOCK = re.compile(
    r'::: \{\.mcq answer="([a-d,]+)"\}\n(.*?)\n:::\n', re.DOTALL)
LINK_ROW = re.compile(r"::: \{\.practice-links\}\n.*?\n:::\n+", re.DOTALL)
FIGURE = re.compile(
    r'^!\[\]\((\.\./slides/img/[\w-]+)\.svg\)\{width="(\d+)" fig-alt="([^"]*)"\}$',
    re.MULTILINE)
IMG_OUT = PRACTICE / "img"
MAX_WIDTH_IN = 5.0  # a wider chart runs tall enough to push itself onto a fresh page


def tex_escape(text: str) -> str:
    return re.sub(r"([&%#_$])", r"\\\1", text)


def figure_repl(m) -> str:
    r"""Markdown figure -> raw LaTeX includegraphics of an rsvg-made PDF.

    pandoc would emit \includesvg (needs Inkscape) and drop the fig-alt;
    this keeps the alt text in the tagged PDF and sizes the figure as on
    the page (CSS pixels at 96 dpi, capped at the text width).
    """
    stem, width, alt = m.group(1), int(m.group(2)), m.group(3)
    src = (PRACTICE / f"{stem}.svg").resolve()
    IMG_OUT.mkdir(exist_ok=True)
    out = IMG_OUT / f"{src.stem}.pdf"
    if not out.exists() or out.stat().st_mtime < src.stat().st_mtime:
        subprocess.run(["rsvg-convert", "-f", "pdf", "-o", str(out), str(src)],
                       check=True)
    w = min(width / 96, MAX_WIDTH_IN)
    return ("\n```{=latex}\n\\begin{center}\n"
            f"\\includegraphics[width={w:.2f}in,alt={{{tex_escape(alt)}}}]"
            f"{{img/{src.stem}.pdf}}\n"
            "\\end{center}\n```\n")


def pandoc(md: str) -> str:
    out = subprocess.run(PANDOC + ["-f", "markdown", "-t", "latex",
                                   "--wrap=preserve"],
                         input=md, capture_output=True, text=True, check=True)
    return out.stdout.strip()


def strip_divs(md: str) -> str:
    lines = []
    for ln in md.split("\n"):
        if re.match(r"^:{3,}(\s|$|\{)", ln):
            continue
        if ln.strip().startswith(": {tbl-colwidths"):
            continue
        lines.append(ln)
    return "\n".join(lines)


def escape_options(md: str) -> str:
    """Lettered option lines become plain paragraphs, never LaTeX lists."""
    out = []
    for ln in md.split("\n"):
        m = re.match(r"^  ([a-d])\. (.*)$", ln)
        if m:
            out.append("")
            out.append(f"{m.group(1)}\\) {m.group(2)}")
        else:
            out.append(ln)
    return "\n".join(out)


def answer_label(ans: str) -> str:
    parts = [f"({a.strip()})" for a in ans.split(",")]
    return parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + " and " + parts[-1]


def convert_page(num: str, with_solutions: bool) -> str:
    src = (PRACTICE / f"practice{num}.qmd").read_text()
    fm = re.match(r"---\n(.*?)\n---\n", src, re.DOTALL).group(1)
    subtitle = re.search(r'subtitle: "(.*)"', fm).group(1)
    body = src[src.index("---\n", 4) + 4:]
    body = body.replace(
        "Work through each problem on paper before you open its **Solution**.", "")
    # The link row under the page title is site navigation, not content.
    body = LINK_ROW.sub("", body)
    body = FIGURE.sub(figure_repl, body)

    if not with_solutions:
        # Questions only: drop solutions, keep everything else, and give the
        # numbered multiple-choice items air between them.
        def mcq_repl(m):
            inner = DETAILS.sub("\n", m.group(2))
            return "MEDSKIP\n\n" + inner + "\n"
        body = MCQ_BLOCK.sub(mcq_repl, body)
        body = DETAILS.sub("\n", body)
        body = escape_options(strip_divs(body))
    else:
        # Solutions only, as in 441: headings, problem numbers, and part
        # labels carry the answers; the questions are not restated.
        mcq_store = []
        def mcq_repl(m):
            ans, inner = m.group(1), m.group(2)
            n = re.search(r"\*\*Q(\d+)\.\*\*", inner).group(1)
            sol = DETAILS.search(inner)
            text = strip_divs(sol.group(1)).strip() if sol else ""
            mcq_store.append(f"**Q{n}.** **{answer_label(ans)}.** {text}")
            return f"\n@@MCQ{len(mcq_store) - 1}@@\n"
        body = MCQ_BLOCK.sub(mcq_repl, body)

        token = re.compile(
            r"(^## [^\n]*)|@@MCQ(\d+)@@|(\*\*\((\w)\)\*\*.*?</details>)",
            re.MULTILINE | re.DOTALL)
        pieces = []
        for m in token.finditer(body):
            if m.group(1):
                pieces.append(m.group(1))
            elif m.group(2):
                pieces.append("MEDSKIP\n\n" + mcq_store[int(m.group(2))])
            else:
                label = m.group(4)
                sol = DETAILS.search(m.group(3))
                text = strip_divs(sol.group(1)).strip() if sol else ""
                if text.startswith("|"):
                    pieces.append(f"**({label})**\n\n{text}")
                else:
                    pieces.append(f"**({label})** {text}")
        body = "\n\n".join(pieces)

    md = f"# Lecture {int(num)}: {subtitle}\n\n" + body
    tex = pandoc(md)
    return tex.replace("MEDSKIP", r"\medskip")


def build(slug: str):
    title, nums = MODULES[slug]
    for kind, suffix in (("Practice Problems", ""), ("Solutions", "_solutions")):
        header = f"{kind}: {title}"
        parts = [PREAMBLE.replace("TITLE_HERE", f"ECON 201 {header}")
                         .replace("HEADER_HERE", header)]
        for n in nums:
            parts.append(convert_page(n, suffix == "_solutions"))
        parts.append("\\end{document}")
        out = PRACTICE / f"practice-{slug}{suffix}.tex"
        out.write_text("\n\n".join(parts) + "\n")
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    slugs = sys.argv[1:] or list(MODULES)
    for slug in slugs:
        if slug not in MODULES:
            sys.exit(f"unknown module {slug}; known: {', '.join(MODULES)}")
        build(slug)
