"""
Build the module-level practice PDFs from the practice pages, as in ECON 441.

    python3 scripts/build_module_practice.py economists-toolkit 03 04

Parses practice/practiceNN.qmd (problems, MCQs, solutions), converts the
markdown with pandoc, and writes practice/practice-<slug>.tex (problems
only) plus practice/practice-<slug>_solutions.tex (problems with solutions),
then compiles both with LuaLaTeX as tagged PDF/UA-2 and veraPDF-gates them.
The qmd pages stay the single source: nothing is retyped here, and the MCQ
answer letters are read back from the answer="" attributes.
"""
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PRACTICE = ROOT / "practice"

TITLES = {"economists-toolkit": "The Economist's Toolkit"}

PANDOC = [shutil.which("pandoc")] if shutil.which("pandoc") else ["quarto", "pandoc"]

PREAMBLE = r"""% !TEX program = lualatex
% Generated by scripts/build_module_practice.py - do not edit by hand.
\DocumentMetadata{
  pdfstandard=UA-2,
  pdfversion=2.0,
  lang=en-US,
  tagging=on
}
\documentclass[11pt]{article}
\usepackage[letterpaper, margin=0.8in, top=0.6in, bottom=0.6in]{geometry}
\usepackage{fontspec}
\setmainfont{Fira Sans}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{calc}
\usepackage{etoolbox}
\usepackage{xcolor}
\definecolor{accent}{HTML}{BF5700}
\usepackage{titlesec}
\titleformat{\section}{\large\bfseries\color{accent}}{}{0pt}{}
\titlespacing*{\section}{0pt}{14pt}{4pt}
\titleformat{\subsection}{\normalsize\bfseries}{}{0pt}{}
\titlespacing*{\subsection}{0pt}{10pt}{2pt}
\usepackage{hyperref}
\hypersetup{pdftitle={TITLE_HERE}, pdfauthor={Div Bhagia}, hidelinks}
\pagestyle{plain}
\setlength{\parindent}{0pt}
\setlength{\parskip}{4pt}
\begin{document}
{\LARGE\bfseries\color{accent} HEADER_HERE}\hfill{\large ECON 201}
\vspace{4pt}
"""

DETAILS = re.compile(
    r'\n?<details class="solution">\s*<summary>Solution</summary>(.*?)</details>\n?',
    re.DOTALL)
MCQ_BLOCK = re.compile(
    r'::: \{\.mcq answer="([a-d,]+)"\}\n(.*?)\n:::\n', re.DOTALL)


def pandoc(md: str) -> str:
    out = subprocess.run(PANDOC + ["-f", "markdown", "-t", "latex",
                                   "--wrap=preserve"],
                         input=md, capture_output=True, text=True, check=True)
    return out.stdout.strip()


def strip_divs(md: str) -> str:
    lines = []
    for ln in md.split("\n"):
        if re.match(r"^:{3,}(\s|$|\{)", ln):
            continue
        if ln.strip().startswith(": {tbl-colwidths"):
            continue
        lines.append(ln)
    return "\n".join(lines)


def escape_options(md: str) -> str:
    """Lettered option lines become plain paragraphs, never LaTeX lists."""
    out = []
    for ln in md.split("\n"):
        m = re.match(r"^  ([a-d])\. (.*)$", ln)
        if m:
            out.append("")
            out.append(f"{m.group(1)}\\) {m.group(2)}")
        else:
            out.append(ln)
    return "\n".join(out)


def answer_label(ans: str) -> str:
    parts = [f"({a.strip()})" for a in ans.split(",")]
    return parts[0] if len(parts) == 1 else ", ".join(parts[:-1]) + " and " + parts[-1]


def convert_page(num: str, with_solutions: bool) -> str:
    src = (PRACTICE / f"practice{num}.qmd").read_text()
    fm = re.match(r"---\n(.*?)\n---\n", src, re.DOTALL).group(1)
    subtitle = re.search(r'subtitle: "(.*)"', fm).group(1)
    body = src[src.index("---\n", 4) + 4:]
    body = body.replace(
        "Work through each problem on paper before you open its **Solution**.", "")

    if not with_solutions:
        # Questions only: drop solutions, keep everything else, and give the
        # numbered multiple-choice items air between them.
        def mcq_repl(m):
            inner = DETAILS.sub("\n", m.group(2))
            return "MEDSKIP\n\n" + inner + "\n"
        body = MCQ_BLOCK.sub(mcq_repl, body)
        body = DETAILS.sub("\n", body)
        body = escape_options(strip_divs(body))
    else:
        # Solutions only, as in 441: headings, problem numbers, and part
        # labels carry the answers; the questions are not restated.
        mcq_store = []
        def mcq_repl(m):
            ans, inner = m.group(1), m.group(2)
            n = re.search(r"\*\*(\d+)\.\*\*", inner).group(1)
            sol = DETAILS.search(inner)
            text = strip_divs(sol.group(1)).strip() if sol else ""
            mcq_store.append(f"**{n}.** **{answer_label(ans)}.** {text}")
            return f"\n@@MCQ{len(mcq_store) - 1}@@\n"
        body = MCQ_BLOCK.sub(mcq_repl, body)

        token = re.compile(
            r"(^## [^\n]*)|@@MCQ(\d+)@@|(\*\*\((\w)\)\*\*.*?</details>)",
            re.MULTILINE | re.DOTALL)
        pieces = []
        for m in token.finditer(body):
            if m.group(1):
                pieces.append(m.group(1))
            elif m.group(2):
                pieces.append("MEDSKIP\n\n" + mcq_store[int(m.group(2))])
            else:
                label = m.group(4)
                sol = DETAILS.search(m.group(3))
                text = strip_divs(sol.group(1)).strip() if sol else ""
                if text.startswith("|"):
                    pieces.append(f"**({label})**\n\n{text}")
                else:
                    pieces.append(f"**({label})** {text}")
        body = "\n\n".join(pieces)

    md = f"# Lecture {int(num)}: {subtitle}\n\n" + body
    tex = pandoc(md)
    return tex.replace("MEDSKIP", r"\medskip")


def build(slug: str, nums):
    title = TITLES[slug]
    for kind, suffix in (("Practice Problems", ""), ("Solutions", "_solutions")):
        header = f"{kind}: {title}"
        parts = [PREAMBLE.replace("TITLE_HERE", f"ECON 201 {header}")
                         .replace("HEADER_HERE", header)]
        for n in nums:
            parts.append(convert_page(n, suffix == "_solutions"))
        parts.append("\\end{document}")
        out = PRACTICE / f"practice-{slug}{suffix}.tex"
        out.write_text("\n\n".join(parts) + "\n")
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    build(sys.argv[1], sys.argv[2:])
